runtime: nodejs18
env: standard
instance_class: F1

handlers:
  - url: /static
    static_dir: build/static
    secure: always

  - url: /(.*\.(json|ico|js|html|png|svg))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|html|png|svg)$
    secure: always

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always

env_variables:
  NODE_ENV: "production"
  REACT_APP_API_URL: "https://kaighostshell-app.an.r.appspot.com/api" 